# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('password', models.CharField(default='tvaran90', max_length=20)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('authentic', models.BooleanField(default=False)),
            ],
        ),
    ]
