# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='display_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
