# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170324_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='authentic',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
