# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170326_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
