# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
