# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20170326_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='username',
        ),
    ]
