# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170326_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
