# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20170326_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='display_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
