# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20170326_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
