# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_person_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='display_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
