# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20170329_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
