# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='user',
        ),
    ]
