# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20170401_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cv',
        ),
        migrations.AddField(
            model_name='person',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
