# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:38
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20170403_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
