# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
