# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20170414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='login.Question'),
        ),
    ]
