# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20170504_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
            ],
        ),
    ]
