# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_quest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quest',
        ),
    ]
