# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('generator_id', models.CharField(max_length=255, null=True)),
                ('action_obj_id', models.CharField(max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('action_verb', models.CharField(default=' recieved a notification.', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_obj_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_notifications', to='contenttypes.ContentType')),
                ('generator_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genrated_notifications', to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
