# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_channels', '0002_auto_20171005_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_obj_id', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('action_verb', models.CharField(default=' recieved a notification.', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True, default='#', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action_obj_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_notifications', to='contenttypes.ContentType')),
                ('generator', models.ManyToManyField(related_name='activity_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='action_obj_ctype',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='generator_ctype',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
