# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0003_auto_20171006_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_verb',
            field=models.CharField(default='You recieved a notification.', max_length=255),
        ),
    ]
