# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0007_auto_20171101_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='generator',
            field=models.ManyToManyField(blank=True, related_name='activity_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
