# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0010_auto_20171112_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.AddField(
            model_name='activity',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
