# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0012_auto_20180217_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='read',
        ),
    ]
