# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0013_remove_activity_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
