# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_channels', '0014_activity_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscriptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_id', models.CharField(max_length=255, unique=True)),
                ('end_point', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('p256dh', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_abscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
